export const GET_CURRENCY_START = "GET_CURRENCY_START";
export const SET_CURRENCY_DATA = "SET_CURRENCY_DATA";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAIL = "GET_CURRENCY_FAIL";
