export const GET_WEATHER_START = "GET_WEATHER_START";
export const SET_WEATHER_DATA = "SET_WEATHER_DATA";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";
